<a href="https://colab.research.google.com/github/Ishatapader/Numpy/blob/main/DA_assignment_py.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
result = [x if x % 2 == 0 else -1 for x in arr]
print(result)

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]


In [2]:
import numpy as np

In [4]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.intersect1d(a, b)
print(c)


[2 4]


In [5]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])
c = np.setdiff1d(a, b)
print(c)

[1 2 3 4]


In [6]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
c = np.where(a == b)
print(c)

(array([1, 3, 5, 7]),)


In [8]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
b = a[(a >= 5) & (a <= 10)]
print(b)

[ 6  9 10]


In [9]:
a = np.array([[0, 1, 2],
                 [3, 4, 5],
                 [6, 7, 8]])
b = a[::-1]
print(b)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


In [11]:
import pandas as pd
import numpy as np

In [12]:
# Import the iris dataset
df=pd.read_csv('IRIS.csv')

In [13]:
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [15]:
sepal_length = df['sepal_length']

mean = np.mean(sepal_length)
median = np.median(sepal_length)
std = np.std(sepal_length)

print("Mean Sepal Length:", mean)
print("Median Sepal Length:", median)
print("Standard Deviation of Sepal Length:", std)

Mean Sepal Length: 5.843333333333334
Median Sepal Length: 5.8
Standard Deviation of Sepal Length: 0.8253012917851409


In [16]:
min = np.min(sepal_length)
max = np.max(sepal_length)
normalized = (sepal_length - min) / (max - min)
print(normalized)

0      0.222222
1      0.166667
2      0.111111
3      0.083333
4      0.194444
         ...   
145    0.666667
146    0.555556
147    0.611111
148    0.527778
149    0.444444
Name: sepal_length, Length: 150, dtype: float64


In [24]:
print("\nMissing values of sepal_length:\n", df['sepal_length'].isnull().sum())



Missing values of sepal_length:
 0
